# Generated by Django 5.2.8 on 2026-02-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarboardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=19)),
                ('starboard_message_id', models.CharField(max_length=19)),
                ('channel_id', models.CharField(max_length=19)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
