# Generated by Django 5.2.8 on 2026-02-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=2048)),
                ('is_down', models.BooleanField()),
                ('downtime_start', models.DateTimeField()),
            ],
        ),
    ]
