# Generated by Django 5.2.8 on 2026-02-21 16:10

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
