# Generated by Django 5.2.8 on 2026-02-21 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_wikipage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
