# Generated by Django 5.2.8 on 2026-02-21 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_wikipage_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
