# Generated by Django 5.2.8 on 2026-02-25 17:31

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_wikipage_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('R', 'Roseverse'), ('T', 'Nintendo TVii')], max_length=1)),
                ('name', models.CharField(max_length=512)),
                ('description', markdownx.models.MarkdownxField()),
                ('solution', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
